apiVersion: skaffold/v1beta15
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: yoshi245/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
          - '**/*.css'
          - '**/*.html'
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
